[package]
name = "nuttx-pr-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.5"
google-generative-ai-rs = { version = "0.3.2", features = ["beta"] }
log = "0.4.22"
octocrab = "0.39.0"
tokio = "1.40.0"
